# Multi-container setup for the ERIP project
version: '3.8'

services:
  django_server:
    build: ./backend/django_server
    ports:
      - "8000:8000"
    env_file:
      - .env

  fastapi_service:
    build: ./backend/fastapi_service
    ports:
      - "8001:8001"
    env_file:
      - .env

  airflow:
    build: ./etl/airflow
    ports:
      - "8080:8080"
    env_file:
      - .env

  react_dashboard:
    build: ./frontend/react_dashboard
    ports:
      - "3000:3000"
    env_file:
      - .env
